dependencies:
  # - smartcontractkit/chainlink-brownie-contracts@1.1.1
  - OpenZeppelin/openzeppelin-contracts@4.4.1
  - smartcontractkit/chainlink@1.3.0

compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink@1.3.0'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.1'
# dotenv: .env
networks:
  default: development
  rinkeby:
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    verify: True
  mainnet-fork-dev:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False
  development:
    verify: False
  ganache-local:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}