dependencies:
  # - smartcontractkit/chainlink-brownie-contracts@1.1.1
  - OpenZeppelin/openzeppelin-contracts@4.4.1
  - smartcontractkit/chainlink@1.3.0
  - aave/aave-v3-core@1.16.0

compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink@1.3.0'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.1'
      - '@aave=aave/aave-v3-core@1.16.0'
dotenv: .env
networks:
  default: development
  kovan:
    weth_token: '0xd0a1e359811322d97991e03f863a0c30c2cf029c'
    lending_pool_address_provider: '0x651b8A8cA545b251a8f49B57D5838Da0a8DFbEF9'
    dai_eth_price_feed: '0x22B58f1EbEDfCA50feF632bD73368b2FdA96D541'
    dai_token: '0xFf795577d9AC8bD7D90Ee22b6C1703490b6512FD'
  rinkeby:
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    verify: True
  mainnet-fork-dev:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False
  development:
    verify: False
  ganache-local:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}