dependencies:
  # - smartcontractkit/chainlink-brownie-contracts@1.1.1
  - OpenZeppelin/openzeppelin-contracts@4.4.1
  - smartcontractkit/chainlink@1.3.0
  - aave/protocol-v2@1.0.1
  # - aave/aave-v3-core@1.16.0

compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink@1.3.0'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.1'
      - "@aave=aave/protocol-v2@1.0.1"
      # - '@aave=aave/aave-v3-core@1.16.0'
dotenv: .env
networks:
  default: mainnet-fork
  mainnet-fork:
    weth_token: "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
    # For mainnet, the link token is the same
    link_token: "0x514910771af9ca656af840dff83e8264ecf986ca"
    aave_link_token: "0x514910771af9ca656af840dff83e8264ecf986ca"
    aave_dai_token: "0x6b175474e89094c44da98b954eedeac495271d0f"
    dai_token: "0x6b175474e89094c44da98b954eedeac495271d0f"
    link_eth_price_feed: "0xDC530D9457755926550b59e8ECcdaE7624181557"
    dai_eth_price_feed: "0x773616E4d11A78F511299002da57A0a94577F1f4"
  kovan:
    lending_pool_addresses_provider: "0x88757f2f99175387ab4c6a4b3067c77a695b0349"
    weth_token: '0xd0a1e359811322d97991e03f863a0c30c2cf029c'
    lending_pool_address_provider: '0x651b8A8cA545b251a8f49B57D5838Da0a8DFbEF9'
    dai_eth_price_feed: '0x22B58f1EbEDfCA50feF632bD73368b2FdA96D541'
    dai_token: '0xFf795577d9AC8bD7D90Ee22b6C1703490b6512FD'
  rinkeby:
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    verify: True
  development:
    verify: False
  ganache-local:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}
  from_key_2: ${PRIVATE_KEY_2}